{% set name = "pyepics" %}
{% set version = "3.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyepics-{{ version }}.tar.gz
  sha256: 689059e9231cd41c8c62cf27581e9c3b4284a99bbd03d1db40710188f9cf4a83
  patches:
    - package_data.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python
      # pkg_resources used in epics/ca.py
    - setuptools
    - epics-base
    - numpy
    - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"
    - pip check
  requires:
    - pip

about:
  home: https://pyepics.github.io/pyepics/
  license: EPICS
  license_file: LICENSE
  summary: Python interface to Epics Channel Access
  dev_url: https://github.com/pyepics/pyepics
  doc_url: https://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - jan-janssen
    - hhslepicka
    - mrakitin
    - stuartcampbell
    - tacaswell
