{% set name = "pyepics" %}
{% set version = "3.5.0" %}
{% set sha256 = "c8154f599ef72ab0d1b49a5c39a76e641ac4f04fc61f3a7294e04e05076c943d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # only include pre-compiled libraries for this platform
    - package_data.patch

build:
  number: 2

requirements:
  host:
    - python
    - pip
  run:
    - python
      # pkg_resources used in epics/ca.py
    - setuptools
    - epics-base
    - numpy
    - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"

about:
  home: https://pyepics.github.io/pyepics/
  license: EPICS
  license_file: LICENSE
  summary: Python interface to Epics Channel Access
  dev_url: https://github.com/pyepics/pyepics
  doc_url: https://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - hhslepicka
    - mrakitin
    - stuartcampbell
    - tacaswell
