{% set name = "pyepics" %}
{% set version = "3.3.1" %}
{% set sha256 = "f66ae493ab4ba45d16f3428bc669615b050c21c5fe648751b2d6d96b36d67b5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
      - python
      - setuptools
      - numpy
      - pyparsing

  run:
      - python
      - setuptools
      - numpy
      - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  # https://github.com/pyepics/pyepics/pull/108
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - CJ-Wright
    - jrmlhermitte
    - stuartcampbell
    - mrakitin
