{% set name = "pyepics" %}
{% set version = "3.5.2" %}
{% set sha256 = "9680af5970c3f4714dd97d33fe13a833d79ae370f69f774889df51c0e4790187" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - package_data.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
      # pkg_resources used in epics/ca.py
    - setuptools
    - epics-base
    - numpy
    - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"

about:
  home: https://pyepics.github.io/pyepics/
  license: EPICS
  license_file: LICENSE
  summary: Python interface to Epics Channel Access
  dev_url: https://github.com/pyepics/pyepics
  doc_url: https://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - hhslepicka
    - mrakitin
    - stuartcampbell
    - tacaswell
