{% set name = "pyepics" %}
{% set version = "3.4.2" %}
{% set sha256 = "771dcdab47c8b6be84505a17860b2e4dce203917efd87b75ce7ad4e61a096390" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
      # pkg_resources used in epics/ca.py
    - setuptools
    - epics-base
    - numpy
    - pyparsing

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics; epics.ca.find_libca()"

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  license_file: LICENSE
  summary: Python interface to Epics Channel Access
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - hhslepicka
    - jrmlhermitte
    - mrakitin
    - stuartcampbell
    - tacaswell
