{% set name = "pyepics" %}
{% set version = "3.4.0" %}
{% set sha256 = "a2913ee5fdab9dfb3d50c0ccb83f7129902e6fdc7ce9c4c1cc9d0d4b2f9c0438" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://github.com/pyepics/{{ name }}/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}
   patches:
     - libca.patch

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
      - python
      - pip
  run:
      - python
      - pip
      - numpy
      - pyparsing
      - epics-base

test:
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices
  commands:
    - python -c "import epics.ca; libca = epics.ca.find_libca(); assert 'lib' in libca; import os; assert epics.ca.find_libca().startswith(os.environ['CONDA_PREFIX']); assert 'clibs' not in epics.ca.find_libca()"

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open
  summary: Python interface to Epics Channel Access
  # https://github.com/pyepics/pyepics/pull/108
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  dev_url: https://github.com/pyepics/pyepics
  doc_url: http://pyepics.github.io/pyepics

extra:
  recipe-maintainers:
    - CJ-Wright
    - jrmlhermitte
    - stuartcampbell
    - mrakitin
    - hhslepicka
